[package]
name = "rust-shell"
version = "0.1.0"
authors = ["Ben Kimock"]

[dependencies]
hostname = "*"
term = "*"
termios = "*"
glob = "*"
itertools = "*"

[profile.release]
lto = true
panic = "unwind"
